apiVersion: v1
kind: Service
metadata:
  namespace: dev-kube
  name: address
  labels:
    app: address
spec:
  type: NodePort
  ports:
    - port: 8081
      nodePort: 31000
  selector:
    app: address
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev-kube
  name: address
spec:
  selector:
    matchLabels:
      app: address
  replicas: ${POD}
  template:
    metadata:
      labels:
        app: address
    spec:
      containers:
        - name: address
          image: address:${IMAGE_TAG}
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
