apiVersion: v1
kind: Service
metadata:
  namespace: dev-kube
  name: user
  labels:
    app: user
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 31001
  selector:
    app: user
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev-kube
  name: user
spec:
  selector:
    matchLabels:
      app: user
  replicas: ${POD}
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: user:${IMAGE_TAG}
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
