apiVersion: v1
kind: ConfigMap
metadata:
  namespace: dev-kube
  name: common
data:
  application.yml: |-
    message:
      hello: Hi Default Profile for Common
      common: Hi Default Profile for Common
    management:
      endpoints:
        web:
          exposure:
            include: info, health, loggers, refresh, env, loggers

---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: dev-kube
  name: common-docker
data:
  application.yml: |-
    message:
      hello: Hi Default Profile for Common
      common: Hi Default Profile for Common
    management:
      endpoints:
        web:
          exposure:
            include: info, health, loggers, refresh, env, loggers
