apiVersion: v1
kind: ConfigMap
metadata:
  namespace: dev-kube
  name: user
data:
  application.yml: |-
    message:
      hello: Hi Default Profile
    server:
      port: 8080
    spring:
      data:
        mongodb:
          database: user
          uri: mongodb://remoteip:27017
      cloud:
        discovery:
          client:
            simple:
              instances:
                address:
                  - uri: http://localhost:8081


---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: dev-kube
  name: user-docker
data:
  application.yml: |-
    message:
      hello: Hi Docker Profile
    spring:
      data:
        mongodb:
          uri: mongodb://mongo:27017
