apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-proxy
  labels:
    app: prometheus-proxy
    component: "server"
    release: prometheus-proxy
  namespace: istio-system
  annotations: {}
