{{- $configName := .Values.config.prefix -}}
{{ range $key, $val := .Values.config.profiles }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ if eq $key "default"}} {{ $configName }} {{ else }} {{ $configName }}-{{ $key }} {{ end }}
  
data:
  application.yml: |-
   {{- toYaml $val | nindent 4}}
{{ end }}