apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: dev-kube
  name: gateway-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  {{- toYaml .Values.gateway.spec | nindent 2 }}
  