apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{ .Values.mongo.name }}-pv"
  labels:
{{ include "infrastructure.labels" . | indent 4 }}
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.mongo.storage.size }}
  accessModes:
    {{- toYaml .Values.mongo.storage.accessModes | nindent 4 }}
  hostPath:
    path:  {{ quote .Values.mongo.storage.hostPath.path }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Values.mongo.name }}-pv-claim"
  labels:
{{ include "infrastructure.labels" . | indent 4 }}
spec:
  storageClassName: manual
  accessModes:
    {{- toYaml .Values.mongo.storage.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.mongo.storage.size }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongo.name }}
  labels:
{{ include "infrastructure.labels" . | indent 4 }}
spec:
  type: {{ .Values.mongo.service.type }}
  ports:
    - port: {{ .Values.mongo.service.containerPort }}
      nodePort: {{ .Values.mongo.service.nodePort }}
  selector:
    app.kubernetes.io/name: {{ .Values.mongo.name }}

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.mongo.name }}
  labels:
{{ include "infrastructure.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.mongo.name }}
  serviceName: {{ .Values.mongo.name }}
  replicas: {{ .Values.mongo.replicas }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.mongo.name }}
    spec:
      volumes:
        - name: "{{ .Values.mongo.name }}-pv-storage"
          persistentVolumeClaim:
            claimName: "{{ .Values.mongo.name }}-pv-claim"
      containers:
        - name: {{ .Values.mongo.name }}
          image: "{{ .Values.mongo.image.repository }}:{{ .Values.mongo.image.tag }}"
          ports:
            - containerPort: {{ .Values.mongo.service.containerPort }}
          volumeMounts:
            - name: "{{ .Values.mongo.name }}-pv-storage"
              mountPath: {{ .Values.mongo.storage.volumePath.path }}
