# Default values for user.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: address
  tag: v1

environments:
  - name: SPRING_PROFILES_ACTIVE
    value: "docker"
service:
  type: NodePort
  containerPort: 8081
  nodePort: 31001

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 1

resources: 
  requests:
    memory: "512Mi"
    cpu: "200m"
  limits:
    memory: "1024Mi"
    cpu: "600m"

healthCheck: 
  httpGet:
    path: /actuator/health
  other:
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 20

config:
  prefix: address
  profiles:
    default:
      message:
        hello: Hi Default Profile for address
    docker:
      message:
        hello: Hi Docker Profilefor address