kind: Service
apiVersion: v1
metadata:
  name: scdf-server
  labels:
    app: scdf-server
    spring-deployment-id: scdf
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 9393
      name: scdf-server
      nodePort: 31561
  selector:
    app: scdf-server
