apiVersion: v1
kind: Service
metadata:
  name: skipper
  labels:
    app: skipper
    spring-deployment-id: scdf
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 7577
      name: http
  selector:
    app: skipper
