apiVersion: v1
kind: ConfigMap
metadata:
  name: user
data:
  application.yml: |-
    message:
      hello: Hi Default Profile

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-docker
data:
  application.yml: |-
    message:
      hello: Hi Docker Profile