apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-ui
  labels:
    app: kafka-ui
spec:
  serviceName: kafka-ui
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui
  template:
    metadata:
      labels:
        app: kafka-ui
    spec:
      containers:
        - name: kafka-ui
          image: provectuslabs/kafka-ui:latest
          env:
            - name: KAFKA_CLUSTERS_0_NAME
              value: local
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: kafka-broker:9092
