apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: dev-kube
  name: mongo-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/data/db"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: dev-kube
  name: mongo-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
