apiVersion: v1
kind: Service
metadata:
  name: adminer
  labels:
    app: adminer
spec:
  type: NodePort
  ports:
    - name: adminer
      port: 8080
      nodePort: 30010
  selector:
    app: adminer
