apiVersion: v1
kind: ConfigMap
metadata:
  namespace: default
  name: address
data:
  application.yml: |-
    spring:
      data:
        mongodb:
          database: address
    server:
      port: 9091

---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: default
  name: address-docker
data:
  application.yml: |-
    spring:
      data:
        mongodb:
          uri: mongodb://mongo:27017
