apiVersion: v1
kind: ConfigMap
metadata:
  namespace: default
  name: user
data:
  application.yml: |-
    message:
      hello: Hi Default Profile
    server:
      port: 9090
    spring:
      data:
        mongodb:
          database: user

      cloud:
        discovery:
          client:
            simple:
              instances:
                address:
                  - uri: http://localhost:9091


---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: default
  name: user-docker
data:
  application.yml: |-
    message:
      hello: Hi Docker Profile
    spring:
      data:
        mongodb:
          uri: mongodb://mongo:27017
